version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_logs:/var/log/postgresql
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "4000:4000"
    networks:  
      - my-network
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:  
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    depends_on:
      - postgres
    networks:  
      - my-network  

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
